# SOPS configuration file
# For more info see https://github.com/getsops/sops
creation_rules:
  - path_regex: secrets/.*\.yaml$
    # Replace with your public AGE key (run: age-keygen -y ~/.config/sops/age/keys.txt)
    age: "age1YOUR_PUBLIC_KEY_HERE"
